[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pg"]

[build.environment]
  NODE_VERSION = "16"
  AWS_LAMBDA_JS_RUNTIME = "nodejs16.x"

[context.production.environment]
  NODE_VERSION = "16"
  AWS_LAMBDA_JS_RUNTIME = "nodejs16.x"

[context.deploy-preview.environment]
  NODE_VERSION = "16"
  AWS_LAMBDA_JS_RUNTIME = "nodejs16.x"
